# Generated by Django 4.1.4 on 2022-12-23 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(default='None', max_length=255),
            preserve_default=False,
        ),
    ]
